---
version: '3'

services:
  example-websocket-node-builder-client:
    image: node:14-slim
    working_dir: /opt/services/example-websocket-node-builder-client
    volumes:
      - ../client/:/opt/services/example-websocket-node-builder-client
    command: ./build.sh

  example-websocket-node-builder-server:
    image: node:14-slim
    working_dir: /opt/services/example-websocket-node-builder-server
    volumes:
      - ../server/:/opt/services/example-websocket-node-builder-server
    command: ./build.sh

